name: Node CI

on:
  - push
  - pull_request

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
            path: ~/.npm
            key: node-cache-${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              node-cache-${{ runner.os }}-npm-
      - run: make install
      - run: make lint
      - run: make test
      - uses: hexlet-components/hello-from-hexlet-action@release